# Generated by Django 4.2.7 on 2023-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('IDPartida', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('CodigoPartida', models.CharField(max_length=255)),
                ('EsPartidaPrivada', models.BooleanField()),
                ('JugadorXID', models.IntegerField()),
                ('JugadorOID', models.IntegerField(blank=True, null=True)),
                ('JugadorIDGanador', models.IntegerField(blank=True, null=True)),
                ('IdPartidaEstado', models.IntegerField()),
            ],
        ),
    ]
