# Generated by Django 4.2.7 on 2023-12-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablero',
            options={'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
        migrations.AlterModelTable(
            name='tablero',
            table='Tablero',
        ),
    ]
